version:              '3'
services:
  sensu:
    build:            sensu-server/
    image:            sensu
    restart:          unless-stopped
    ports:
      - "3000:3000"
      - "4567:4567"
    networks:
      front:
        ipv4_address: 172.16.238.10

  redis:
    image:            redis:latest
    restart:          unless-stopped
    command:          redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      front:
        ipv4_address: 172.16.238.30

  rabbitmq:
    image:            rabbitmq
    hostname:         rabbitmq
    restart:          unless-stopped
    env_file:
      - rabbitmq-server/rabbitmq.env
    ports:
      - "5672:5672"   # daemon API
      - "15672:15672" # management API
    networks:
      front:
        ipv4_address: 172.16.238.20

networks:
  front:
    driver:           bridge
    ipam:
      driver:         default
      config:
      - subnet:       172.16.238.0/24
        gateway:      172.16.238.1
