version:      '3'
services:
  sensu:
    hostname: sensu
    build:    sensu-server/
    image:    sensu
    restart:  unless-stopped
    ports:
      - "3000:3000"
      - "4568:4568"
    networks:
      - front


  redis:
    hostname: redis
    image:    redis:latest
    restart:  unless-stopped
    command:  redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - front


  rabbitmq:
    image:    rabbitmq
    hostname: rabbitmq
    restart:  unless-stopped
    env_file:
      - rabbitmq-server/rabbitmq.env
    ports:
      - "5672:5672"   # daemon API
      - "15672:15672" # management API
    networks:
      - front


networks:
  front:
    driver:   bridge
